services:
  playzio-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playzio
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: